apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: oqsmeds1j-python 
  janus-idp.io/tekton: oqsmeds1j-python
  backstage.io/kubernetes-id: oqsmeds1j-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oqsmeds1j-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml